CAMPAIGN_MONITOR_API_KEY   = ENV['CAMPAIGN_MONITOR_API_KEY']
CAMPAIGN_MONITOR_CLIENT_ID = ENV['CAMPAIGN_MONITOR_CLIENT_ID']
CAMPAIGN_MONITOR_LIST_ID   = ENV['CAMPAIGN_MONITOR_LIST_ID']

FAILTALE = {
  :allow_registration => false,
  :allow_invitations  => true,
  :google_analytics   => ENV['GOOGLE_ANALYTICS']
}